version: "3.8"

services:
  db:
    image: library/postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - env/.env
    depends_on:
      - db
    restart: "on-failure"

volumes:
  postgres_data:
  static_volume:
  media_volume:
